# Generated by Django 5.2.7 on 2026-02-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_tag_options_tag_color_tag_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tag',
            name='unique_tag_per_user',
        ),
    ]
